export const GET_EMPLOYEE_DETAILS = "GET_EMPLOYEE_DETAILS"
export const ADD_EMPLOYEE = "ADD_EMPLOYEE"
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE"
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE"